# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:

version: "3"

services: 
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    network_mode: host
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/conf.d:/etc/nginx/conf.d"
      - "./nginx/share/html:/usr/share/nginx/html"
      - "./nginx/log:/var/log/nginx"
